# Generated by Django 4.2.5 on 2023-09-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0006_remove_order_items_remove_order_user_delete_cartitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
