# Generated by Django 4.2.5 on 2023-09-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0010_cartitem_order_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductId', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('SubCategory', models.CharField(max_length=100)),
                ('ProductType', models.CharField(max_length=100)),
                ('Colour', models.CharField(max_length=100)),
                ('Usage', models.CharField(max_length=100)),
                ('ProductTitle', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
            ],
        ),
    ]
