# Generated by Django 4.2.5 on 2023-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0011_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
