# Generated by Django 4.2.5 on 2023-09-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0012_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductId',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
