# Generated by Django 4.2.5 on 2023-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0015_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=300),
        ),
    ]
