# Generated by Django 4.2.5 on 2023-10-03 11:12

from django.db import migrations, models
import django.db.models.deletion
import restApi.models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0016_alter_address_city_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restApi.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=restApi.models.calculate_default_date),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
    ]
