# Generated by Django 4.2.5 on 2023-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0017_order_address_order_created_at_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2023-10-10 20:45:38.223612+00:00'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='restApi.products'),
        ),
    ]
