# Generated by Django 4.2.5 on 2023-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0018_alter_order_created_at_alter_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2023-10-18 16:52:20.964977+00:00'),
        ),
    ]
