# Generated by Django 4.2.5 on 2023-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0019_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2023-10-18 16:53:51.478957+00:00'),
        ),
    ]
