# Generated by Django 4.1.7 on 2023-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0020_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default='2023-10-24 19:22:26.452629+00:00'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.JSONField(default=list),
        ),
    ]
